getgenv().KiTTYWARE = {
    autoPrepare = {
        Usernames = {


"TWUYgRjp",
"QiQw123u",
"q2QV6RLo",
"LxQLJgar",
"REKdCvsc",
"NmoeYdnG",
"khR9InDY",
"pHBrpIFh",
"LFZu3gtp",
"TsFj1L6W",
"UlMmYVGB",
"zKIWooAx",
"T0ztvUiQ",
"MyoY2gDP",
"N3uGujYF",
"HAElvhMU",
"FCidLVap",
"vWKeUDAs",
"B5o28oxy",
"do3HuBIf",
"eVZH4OA5",
"mP3QvrCu",
"nfxHGxDs",
"apd3kpZ9",
"IyVoW9Zz",
"UnuDIBmr",
"mXdBy5nL",
"vW6APahT",
"IkoGfvno",
"AchNf2XY",
"jChSJ8SJ",
"wlFmqq09",
"vnMfs057",
"zdVP0Eij",
"BfpX3Xss",
"gfzSNcWd",
"CFJ2pIwa",
"DR5S586b",
"mTiS9Uap",
"kfop1Cjj",
"xd6X1LcN",
"wDYZ6wNW",
"acA0vboV",
"qsdHxR2D",
"Ncdu1Rbm",
"C1xdYoIV",
"sIp7TiYP",
"Xhz5odwg",
"vO7aZPqj",
"K72TyAYm",
"hFBJ3TIu",
"aPYfipv9",
"pQSEZzmo",
"rjt2zfd8",
"H8dpM4l2",
"mVP6M5Q9",
"n0JuVfRA",
"RUDMV1RM",
"LEUyNj87",
"jOgzHOtt",
"CSwrKYI7",
"bB4HrW4f",
"oid8obRv",
"yh1E1GxN",
"toIgLaEO",
"U3btBUTX",
"ZfQ3wXDg",
"sCzbNqCq",
"mlmTtvH4",
"RtEjs3K1",
"RCTdKghw",
"wf0X3eU7",
"SDgEz3iy",
"U555Tpfh",
"vhjqGZiv",
"GkoqdX1K",
"iez70Ipp",
"MCcmDAuM",
"WuC6fzww",
"UMVLtUep",
"RuhMT9LH",
"fybEBciZ",
"YCfYMjwV",
"XnwJ0nS9",
"AtWYgIJY",
"zOFvMtls",
"tK7doywU",
"PIkjyMiQ",
"czXyE7Wv",
"zfWlvd3v",
"pg13lS1Q",
"Yyil7wEk",
"lo1RAyIy",
"JbLYQxNw",
"L1dWnKxU",
"At5ibO4R",
"o7WrG7Xh",
"cH4qMHEh",
"b4yIpGzX",
"ZHM9g5d9",
"GeJKyasl",
"gahF3KMq",
"dohE8ev1",
"DtSDFwev",
"vej98QGW",
"VgWBlj57",
"AYH1E5bY",
"kg29ZvA9",
"uzpag48j",
"JGiwVSUI",
"bGGmHlhr",
"WIuaHZl0",
"mc8Pq7vT",
"PR9fAXfo",
"xeqKxJnn",
"yDsauq2J",
"GsNOUe75",
"YRvadYFJ",
"AlmkMzyb",
"QyHdp5I5",
"ve0JlD0t",
"SsU24MRj",
"iQ0IGLNI",
"k1YRGn2Z",
"MjppNlbm",


            
        },
        mailConfig = {
            {Class = "Pet", Name = "Alien Parasite", Tier = 2, Shiny = false, Amount = 40},
            {Class = "Potion", Name = "Coins", Tier = 5, Shiny = false, Amount = 6},
            {Class = "Enchant", Name = "Coins", Tier = 5, Shiny = false, Amount = 2},
            --{Class = "Currency", Name = "Diamonds", Tier = nil, Shiny = false, Amount = 100000},
        },
    }
}

loadstring(game:HttpGet("https://raw.githubusercontent.com/xnazov/KITTYWARE_PS99/main/autoPrepare"))()
