getgenv().KiTTYWARE = {
    autoPrepare = {
        Usernames = {

"qGdwVcoT",
"ooWPby8A",
"n1RPwlkG",
"gFjJiKk8",
"PYjqYrGo",
"ipCUrtsJ",
"rhDv3vOX",
"hUiQ6uTE",
"y7RHsSHC",
"pi2MYbhn",
"e2JgMqO2",
"bZn1b830",
"PVe2OsLJ",
"rKXzYjlK",
"oOoLp2mv",
"nscHb6TE",
"CnNvFeO2",
"JEBEPnel",
"uwbGzxst",
"dAzQ9qIE",
"U734O3Ug",
"oRhNGsqJ",
"TkTiQJod",
"cdo12xSN",
"gmoicMxo",
"XscYr7yN",
"rdbeQLFg",
"kwne09ny",
"TIlxWqOO",
"PxdDWagl",
"sVhYRP0p",
"oaYq4Gzn",
"dMOxF5dl",
"yblRAvZ7",
"d8KlHKkN",
"JKOTlEWU",
"EHJ6VXOc",
"M1TqLpnw",
"eKG5ylRr",
"A5gnEHCP",
"LFzFMwBt",
"tKmBrm5V",
"aTIj63JN",
"vWDt7BSj",
"kmNWjAxO",
"FH9BwvLk",
"z7dKmI3S",
"SHQeSPzR",
"Izu6CKaP",
"hqS8j1sa",
"DjYCLwPS",
"JJGNJpr1",
"vzXeTUD8",
"e484xVa5",
"l75a92KY",
"QkWqqpTl",
"b06A2Sh4",
"vwpvyNDB",
"EZP4NOF4",
"c9wAwYTM",
"Uk3GlrlG",
"yOXDRsIz",
"YER5OQYv",
"WXTlmWDR",
"mW3CcK9b",
"ucsUmW3A",
"FBxE7prs",
"BO502F82",
"Qk8MGt2p",
"nXhOG3Hr",
"oWZIrlhx",
"tsAmgYAw",
"uXvT9OYI",
"AP8QhXQM",
"VkqAQfpy",
"mGcCFPOG",
"vd5V2kSw",
"gAMnukEm",
"RK6eiNyF",
"slMhReHs",
"y6wxCbOD",
"EAePdyUC",
"OSCXm0Zn",
"BKOtei34",
"yqEEteE3",
"denxe1ZN",
"BtcG3RoL",
"T4ySHG0O",
"DfqM8p09",
"sfOR3nsE",
"ZnkM9qMr",
"NR4Xbflr",
"i51JHLP6",
"Qr4ZLhcI",
"Iz1oeBOJ",
"VHv9QoGP",
"Bxm4d1mJ",
"d62Wq6ER",
"LhKOgPqz",
"Wv3DR53i",


    },
 sendPets = true, 
        petConfig = {
            {petName = "Frostbyte Bat", petType = "Rainbow", petAmount = 40}
        },
        
        sendPots = true,
        potConfig = {
            {potName = "Coins", potTier = 5, potAmount = 10},
        },
        
        sendEnch = true,
        enchConfig = {
            {enchName = "Coins", enchTier = 5, enchAmount = 2}
        },
        
        sendFruit = true,
        fruitConfig = {
            {fruitName = "Rainbow", fruitAmount = 50}
        },
        
        sendGems = false,
        gemsAmount = 40000,
    }
}
loadstring(game:HttpGet("https://api.luarmor.net/files/v3/loaders/920918ba6d30cd410dacee97916c773e.lua"))()
