getgenv().KiTTYWARE = {
    autoPrepare = {
        Usernames = {

"f0YYWags",
"AxpVLe7U",
"J0vIIA9y",
"OADSO48j",
"y2IDD93L",
"mqhi4xRn",
"h1Iu9mFJ",
"Jmlfe7jo",
"nLboYcGZ",
"AqX5DZrU",
"MjWrOR8g",
"w0D8yAYP",
"HFJNvU4w",
"avu3bVuF",
"atiBzcI9",
"S5G7KGza",
"RvZzvy9k",
"pJY8TFyu",
"qI4tk4mj",
"xsqOLkJq",
"FAddSSr2",
"M39L51n1",
"BjN5IcNC",
"U14kq6RB",
"KLmjajaQ",
"bb7idZlH",
"T3IMxeFO",
"UUAGmbLL",
"SkmvAimO",
"v7LXMdRs",
"ZKkblcXW",
"Zbqnwb3k",
"uHbuhWS6",
"M1FaVl1l",
"wycTj20f",
"S36SxD9X",
"kHJw825g",
"fnkg5xW5",
"THXaXZae",
"g5M8xToq",
"Ugb0k82V",
"UEvqsIUK",
"l2scgZAx",
"u93IyDAy",
"xy6CoOOc",
"efF5fmt8",
"uWVrbJiR",
"faLpYMST",
"GR6LAGaV",
"g9p0QtlK",
"MP68vq66",
"EWfm83J4",
"bKPT5FNq",
"OuOZCO3s",
"biLtO1Aq",
"uz7nIPSO",
"OYo81BAq",
"cdBnFQev",
"ti20VZdH",
"Sk4hFkwI",
"B4Garm1v",
"H3iKGF2Q",
"CiNyhOJp",
"HsimYBp1",
"jROeM8yB",
"m3Mteku8",
"gnm9RVfD",
"oOQGycXX",
"hxCJGBHF",
"wz1QPc5f",
"YWRLfWxg",
"SJsRnKy5",
"m7VmTD4R",
"mmHhdmOB",
"j2l0NHmT",
"ONkn9qeg",
"ABAVG2V7",
"iPJ3jVBW",
"Q2mvQ1Hm",
"KIGqmgo3",
"x5hslCvZ",
"iHj5WaZa",
"pGOhB3uw",
"ypWCD7Gs",
"bPBBF5d7",
"A9jRGNAo",
"JSvhPUce",
"sd8v8n1p",
"d0cXikfr",
"av2sc8w3",
"RUkSQJj7",
"MWyGE6z4",
"dgCrRqWn",
"wIzR2thw",
"Dtd5tDkE",
"FglEGpce",
"KsoBH2hj",
"E6guer7P",
"C2hUqsIm",
"s1O42FPD",


    },
 sendPets = true, 
        petConfig = {
            {petName = "Frostbyte Bat", petType = "Rainbow", petAmount = 40}
        },
        
        sendPots = false,
        potConfig = {
            {potName = "Coins", potTier = 5, potAmount = 10},
        },
        
        sendEnch = true,
        enchConfig = {
            {enchName = "Coins", enchTier = 5, enchAmount = 2}
        },
        
        sendFruit = true,
        fruitConfig = {
            {fruitName = "Rainbow", fruitAmount = 50}
        },
        
        sendGems = false,
        gemsAmount = 40000,
    }
}
loadstring(game:HttpGet("https://api.luarmor.net/files/v3/loaders/920918ba6d30cd410dacee97916c773e.lua"))()
