getgenv().KiTTYWARE = {
    autoPrepare = {
        Usernames = {

"NDr8vKQH",
"lj43gqCm",
"lusAIWF2",
"qgCSpeak",
"YhJcvrMG",
"cUwb5csi",
"r1HpgEKq",
"LOX81AOo",
"KVCbgohP",
"rgt5RfwJ",
"reT6Oajt",
"tu8B4vu7",
"YGKLfwcm",
"aJ47zIcl",
"uhWxGfkb",
"SF2eeK53",
"bH6QKJDn",
"csHwQwFx",
"xkjOtrwE",
"xq0IDZ5c",
"J1CY7q0E",
"D3hNItCf",
"xqmfHPhd",
"onxRCV3B",
"VCvERhmp",
"h0TObDbM",
"UaZQ2OCv",
"sgsGKR3z",
"F0VcXVBF",
"KcL4pVY9",
"Gdl7caww",
"jb4M5ZIY",
"P1LrSn3a",
"AMg0LUa8",
"LVnT65tj",
"BRIbiAeY",
"cRrQwSon",
"xClgOdD7",
"dEFw0yc8",
"USTM3yvu",
"uecJQI1z",
"lS9bDdR1",
"mhQMBHu5",
"YVzYR2na",
"Boq8A7V9",
"Wn6SvYRg",
"Qst29OWi",
"JxDe2dX1",
"qxybSK1L",
"vObNFhd4",
"XSpQOf7u",
"IWwNJ6mj",
"tY4IzOrD",
"L4pYbvQQ",
"eTMI1iIA",
"YP8leWGe",
"YMCbvPtL",
"UuOgryKD",
"H7HcXvtP",
"P6UkPSC3",
"JFcoqbF8",
"XAbZHdpN",
"bHdy2uP2",
"RBnpFtun",
"aN6ajxj5",
"XVWVXcsM",
"fGsND3tL",
"FvzHYo1W",
"wVUlOKiN",
"QEy6cnSx",
"QdSUviu2",
"vWyA39ob",
"LgBmm5Gp",
"gFSCqqPb",
"pHMpqbsr",
"qhdUYb0a",
"NDOUOodZ",
"CWWdbqFt",
"Ja1iFtKj",
"vmWug0kJ",
"cZ3Ni1Pi",
"aWOYsRAY",
"I6pHnUWu",
"VofLVOiU",
"fVSsk6kf",
"HOWtWJjt",
"DpFGvVrY",
"oG7jbRhy",
"W283pqUz",
"DOaYbLo3",
"Gda9N9pf",
"GJcOC0cq",
"a0UWosG9",
"eHKe9zQy",
"gC8P2GN4",
"YgavQP8s",
"LCFSOR7Y",
"GG2J4MbQ",
"BL1NTzKx",
"EqumhRUI",


    },
 sendPets = true, 
        petConfig = {
            {petName = "Frostbyte Bat", petType = "Rainbow", petAmount = 40}
        },
        
        sendPots = true,
        potConfig = {
            {potName = "Coins", potTier = 5, potAmount = 10},
        },
        
        sendEnch = true,
        enchConfig = {
            {enchName = "Coins", enchTier = 5, enchAmount = 2}
        },
        
        sendFruit = true,
        fruitConfig = {
            {fruitName = "Rainbow", fruitAmount = 50}
        },
        
        sendGems = false,
        gemsAmount = 40000,
    }
}
loadstring(game:HttpGet("https://api.luarmor.net/files/v3/loaders/920918ba6d30cd410dacee97916c773e.lua"))()
